<?php

return [
    'ROUTE_PREFIX' => env('UNBOUND_ROUTE_PREFIX', ''),
    'ROUTE_MIDDLEWARE' => env('UNBOUND_ROUTE_MIDDLEWARE', 'web'),
    'API_ROUTE_PREFIX' => env('UNBOUND_API_ROUTE_PREFIX', 'api'),
    'API_ROUTE_MIDDLEWARE' => env('UNBOUND_API_ROUTE_MIDDLEWARE', 'api')


];